describe("t.fn.combined", function()
  local t, combined
  setup(function()
    t = require "t"
    combined = t.fn.combined
  end)
  it("tostring + tonumber", function()
    local f = combined(tostring, tonumber)
    assert.equal(777, f(777))
    assert.equal(777, f('777'))
  end)
  it("tostring + string.toupper", function()
    local f = combined(tostring, string.upper)
    assert.equal('NEWTON CLASS', f('newton class'))
    assert.equal('MICRO SOFT', f('micro soft'))
  end)
  it("tonumber", function()
    local f = combined(tonumber)
    assert.equal(777, f(777))
    assert.equal(777, f('777'))
  end)
  it("nil", function()
    local f = combined(nil, nil)
    assert.equal('russia', f('russia'))
  end)
end)
