describe("number.byte", function()
  local t, is, byte
  setup(function()
    t = require "t"
    is, byte = t.is, t.number.byte
  end)
  it("meta", function()
    assert.is_true(is.callable(byte))
  end)
  it("positive", function()
    for i=0,255 do
      assert.equal(i, byte(i))
    end
  end)
  it("negative", function()
    assert.is_nil(byte(math.pi))
    assert.is_nil(byte(-1))
    assert.is_nil(byte(256))
    assert.is_nil(byte(""), '""')
    assert.is_nil(byte(' '))
    assert.is_nil(byte('  '))
    assert.is_nil(byte('	'))
    assert.is_nil(byte('		'))
    assert.is_nil(byte("	\r 	"))
    assert.is_nil(byte("	\n 	"))
    assert.is_nil(byte(false), 'false')
    assert.is_nil(byte(true), 'false')
    assert.is_nil(byte({}), '{}')
    assert.is_nil(byte("false"), '"false"')
    assert.is_nil(byte("0"), '"0"')
    assert.is_nil(byte("FALSE"), '"FALSE"')
  end)
  it("nil", function()
    assert.is_nil(byte(nil), 'nil')
    assert.is_nil(byte(), 'no arg')
  end)
end)