describe("number.integer", function()
  local t, is, integer
  setup(function()
    t = require "t"
    is, integer = t.is, t.number.integer
  end)
  it("meta", function()
    assert.is_true(is.callable(integer))
  end)
  it("integer", function()
    assert.equal(0, integer(0))
    for i=1,512 do
      assert.equal(i, integer(i))
      assert.equal(-i, integer(-i))
    end
  end)
  it("integer", function()
    assert.is_nil(integer(-math.pi))
    assert.is_nil(integer(math.pi))
    assert.is_nil(integer(1/2))
    assert.is_nil(integer(-(1/2)))
    assert.is_nil(integer(""), '""')
    assert.is_nil(integer(' '))
    assert.is_nil(integer('  '))
    assert.is_nil(integer('	'))
    assert.is_nil(integer('		'))
    assert.is_nil(integer("	\r 	"))
    assert.is_nil(integer("	\n 	"))
    assert.is_nil(integer(false), 'false')
    assert.is_nil(integer(true), 'false')
    assert.is_nil(integer({}), '{}')
    assert.is_nil(integer("false"), '"false"')
    assert.is_nil(integer("0"), '"0"')
    assert.is_nil(integer("FALSE"), '"FALSE"')
  end)
  it("nil", function()
    assert.is_nil(integer(nil), 'nil')
    assert.is_nil(integer(), 'no arg')
  end)
end)