describe("number.natural", function()
  local t, is, natural
  setup(function()
    t = require "t"
    is, natural = t.is, t.number.natural
  end)
  it("meta", function()
    assert.is_true(is.callable(natural))
  end)
  it("positive", function()
    for i=1,512 do
      assert.equal(i, natural(i))
    end
  end)
  it("negative", function()
    assert.is_nil(natural(math.pi))
    assert.is_nil(natural(-1))
    assert.is_nil(natural(0))
    assert.is_nil(natural(""), '""')
    assert.is_nil(natural(' '))
    assert.is_nil(natural('  '))
    assert.is_nil(natural('	'))
    assert.is_nil(natural('		'))
    assert.is_nil(natural("	\r 	"))
    assert.is_nil(natural("	\n 	"))
    assert.is_nil(natural(false), 'false')
    assert.is_nil(natural(true), 'false')
    assert.is_nil(natural({}), '{}')
    assert.is_nil(natural("false"), '"false"')
    assert.is_nil(natural("0"), '"0"')
    assert.is_nil(natural("FALSE"), '"FALSE"')
  end)
  it("nil", function()
    assert.is_nil(natural(nil), 'nil')
    assert.is_nil(natural(), 'no arg')
  end)
end)