describe("number.negative", function()
  local t, is, negative
  setup(function()
    t = require "t"
    is, negative = t.is, t.number.negative
  end)
  it("meta", function()
    assert.is_true(is.callable(negative))
  end)
  it("positive", function()
    for i=1,512 do
      assert.equal(-i, negative(-i))
    end
  end)
  it("negative", function()
    assert.is_nil(negative(math.pi))
    assert.is_nil(negative(0))
    assert.is_nil(negative(1))
    assert.is_nil(negative(""), '""')
    assert.is_nil(negative(' '))
    assert.is_nil(negative('  '))
    assert.is_nil(negative('	'))
    assert.is_nil(negative('		'))
    assert.is_nil(negative("	\r 	"))
    assert.is_nil(negative("	\n 	"))
    assert.is_nil(negative(false), 'false')
    assert.is_nil(negative(true), 'false')
    assert.is_nil(negative({}), '{}')
    assert.is_nil(negative("false"), '"false"')
    assert.is_nil(negative("0"), '"0"')
    assert.is_nil(negative("FALSE"), '"FALSE"')
  end)
  it("nil", function()
    assert.is_nil(negative(nil), 'nil')
    assert.is_nil(negative(), 'no arg')
  end)
end)