describe("match.x32", function()
	local t, is, x32
	setup(function()
    t = require 't'
    is = t.is
    x32 = t.pat.x32
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(x32))
  end)
  it("positive", function()
    assert.equal('ba1f2511fc30423bdbb183fe33f3dd0f', x32('ba1f2511fc30423bdbb183fe33f3dd0f'))
  end)
  it("negative", function()
    assert.is_nil(x32('8.8.8.8'))
    assert.is_nil(x32('com'))
    assert.is_nil(x32('.'))
    assert.is_nil(x32('.local'))
    assert.is_nil(x32('local'))
    assert.is_nil(x32({}))
    assert.is_nil(x32({'type'}))
    assert.is_nil(x32(0))
    assert.is_nil(x32(''))
    assert.is_nil(x32(false))
    assert.is_nil(x32(true))
    assert.is_nil(x32('xxx.site.info'))
  end)
  it("nil", function()
    assert.is_nil(x32(nil))
    assert.is_nil(x32())
  end)
end)