describe("is.array", function()
	local t, is, array
	setup(function()
    t = require "t"
    is = t.is
    array = t.array
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.array)
    assert.truthy(is.callable(is.array))
  end)
  it("positive", function()
    assert.is_true(is.array(array))
    assert.is_true(is.array(array()))
    assert.is_true(is.array(array({})))
    assert.is_true(is.array(array({'type'})))
  end)
  it("negative", function()
    assert.is_nil(is.array({}))
    assert.is_nil(is.array({'type'}))
    assert.is_nil(is.array(0))
    assert.is_nil(is.array(''))
    assert.is_nil(is.array(false))
    assert.is_nil(is.array(true))
  end)
  it("nil", function()
    assert.is_nil(is.array(nil))
    assert.is_nil(is.array())
  end)
end)