describe("is.bulk", function()
  local t --, is
  setup(function()
    t = require "t"
--    is = t.is
  end)
  it("bulk", function()
    assert.not_is_bulk()
    assert.not_is_bulk(nil)
    assert.not_is_bulk(1)
    assert.not_is_bulk("")
    assert.not_is_bulk(true)
    assert.not_is_bulk(false)
    assert.not_is_bulk(string.upper)
    assert.not_is_bulk({})

    assert.bulk(t.set)
    assert.bulk(t.set())
    assert.bulk(t.set:of(tostring))
    assert.bulk(t.set:of(tostring)())
    assert.bulk({''})
    assert.bulk({''})
    assert.bulk({"x"})
    assert.bulk({"x", "y"})
    assert.bulk({1})
    assert.bulk(t.array)
    assert.bulk(t.array())
    assert.bulk(t.array({}))
    assert.bulk(t.array({1}))
  end)
end)