describe("is.eq", function()
  setup(function()
    require "t"
  end)
  it("eq", function()
      assert.eq()
      assert.eq(nil)
      assert.eq(nil, nil)
      assert.eq('', '')
      assert.eq(3, 3)
      assert.eq(true, table({x=1}))
      assert.eq('x', 'x')
      assert.eq({a=1}, {a=1})
      assert.eq({a=1, b={}}, {a=1, b={}})
      assert.eq({a=1, b={c={777}}}, {a=1, b={c={777}}})
      assert.not_eq({a=1}, {a='1'})
      assert.eq({'a'}, {'a'})
      assert.not_eq({'a'}, {'b'})

      local a = setmetatable({}, {__eq=function() return true end})
      local b = setmetatable({}, {__eq=function() return false end})
      assert.eq(a, b)
      assert.not_eq(b, a)
  end)
end)