describe("is.natural", function()
  local t, is
  setup(function()
    t = require "t"
    is = t.is
  end)
  it("meta", function()
    assert.callable(is.natural)
  end)
  it("positive", function()
    for i=1,512 do
      assert.is_true(is.natural(i))
    end
  end)
  it("negative", function()
    assert.is_nil(is.natural(math.pi))
    assert.is_nil(is.natural(-1))
    assert.is_nil(is.natural(0))
    assert.is_nil(is.natural(""), '""')
    assert.is_nil(is.natural(' '))
    assert.is_nil(is.natural('  '))
    assert.is_nil(is.natural('	'))
    assert.is_nil(is.natural('		'))
    assert.is_nil(is.natural("	\r 	"))
    assert.is_nil(is.natural("	\n 	"))
    assert.is_nil(is.natural(false), 'false')
    assert.is_nil(is.natural(true), 'false')
    assert.is_nil(is.natural({}), '{}')
    assert.is_nil(is.natural("false"), '"false"')
    assert.is_nil(is.natural("0"), '"0"')
    assert.is_nil(is.natural("FALSE"), '"FALSE"')
  end)
  it("nil", function()
    assert.is_nil(is.natural(nil), 'nil')
    assert.is_nil(is.natural(), 'no arg')
  end)
end)