describe("to.izpositive", function()
  local t, is, to
  setup(function()
    t = require "t"
    is, to = t.is, t.to
  end)
  it("meta", function()
    assert.is_true(is.callable(to.izpositive))
  end)
  it("positive", function()
    assert.equal(1, to.izpositive(1))
    assert.equal(7, to.izpositive(7))
    assert.equal(0, to.izpositive('0'))
    assert.equal(12, to.izpositive('12'))
    assert.equal(77, to.izpositive('77'))

    assert.is_nil(to.izpositive('-1'))
    assert.is_nil(to.izpositive('0.2'))
    assert.is_nil(to.izpositive('12.1'))
    assert.is_nil(to.izpositive('77.4'))
  end)
  it("negative", function()
    assert.is_nil(to.izpositive(-1))
    assert.is_nil(to.izpositive(-7))
    assert.is_nil(to.izpositive('any'))
    assert.is_nil(to.izpositive('true'))
    assert.is_nil(to.izpositive('TRUE'))
    assert.is_nil(to.izpositive(true))
    assert.is_nil(to.izpositive({x=1}))
    assert.is_nil(to.izpositive({{}}))

    assert.is_nil(to.izpositive(""))
    assert.is_nil(to.izpositive(' '))
    assert.is_nil(to.izpositive('  '))
    assert.is_nil(to.izpositive('	'))
    assert.is_nil(to.izpositive('		'))
    assert.is_nil(to.izpositive("	\r 	"))
    assert.is_nil(to.izpositive("	\n 	"))
    assert.is_nil(to.izpositive(false))
    assert.is_nil(to.izpositive({}))
    assert.is_nil(to.izpositive("false"))
    assert.is_nil(to.izpositive("FALSE"))
  end)
  it("nil", function()
    assert.is_nil(to.izpositive(nil))
    assert.is_nil(to.izpositive())
  end)
end)