describe("boolean", function()
  setup(function()
    require "t"
  end)
  it("toboolean", function()
    assert.callable(toboolean)
    assert.is_true(toboolean(7))
    assert.is_false(toboolean(0))
  end)
end)
