describe("fields", function()
	local t, is, fields
	setup(function()
    t = require "t"
    is = t.is
    fields = t.fields
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(fields))

    assert.is_table(fields)
    assert.is_table(getmetatable(fields))
  end)
  it("positive", function()
    local o=fields({a=tostring, b=tonumber})
    assert.same({a='true', b=77}, o({a=true, b='77'}))
    assert.same({a='34', b=0}, o({a=34, b='0'}))
  end)
  it("negative", function()
    local o=fields({a=tostring, b=tonumber})
    assert.is_nil(o({b='none'}).b)
    assert.is_nil(o({b=''}).b)
    assert.is_nil(o({b=true}).b)
    assert.is_nil(o({b=false}).b)
    assert.is_nil(o({b=string.lower}).b)
  end)
  it("nil", function()
    local o=fields({a=tostring, b=tonumber, x=nil})
    assert.is_nil(o({x=99}).x)
    assert.is_nil(o({x=''}).x)
    assert.is_nil(o({x='x'}).x)
    assert.is_nil(o({x=true}).x)
  end)
end)