describe("assert callable", function()
	local t
	setup(function()
		t = require "t"
	end)
  it("positive", function()
    assert.callable(table)
    assert.callable(table.remove)
    assert.callable(t)
    assert.callable(t.is)
  end)
  it("negative", function()
    assert.not_callable("some")
    assert.not_callable(true)
    assert.not_callable({7})
    assert.not_callable(1)
    assert.not_callable("1")
  end)
  it("nil", function()
    assert.not_callable(nil)
    assert.not_callable()
  end)
end)
