describe("assert iterable", function()
	local t
	setup(function()
		t = require "t"
	end)
  it("positive", function()
    assert.iterable(table)
    assert.iterable(t)
    assert.iterable(t.is)
    assert.iterable({7})
  end)
  it("negative", function()
    assert.not_iterable("some")
    assert.not_iterable(true)
    assert.not_iterable(1)
    assert.not_iterable("1")
    assert.not_iterable(table.remove)
  end)
  it("negative", function()
    assert.not_iterable(nil)
    assert.not_iterable()
  end)
end)
