describe("assert same_values", function()
	setup(function() require "t" end)
  it("positive", function()
		assert.same_values({"one", "two", "three", "four"}, {"one", "two", "three", "four"})
		assert.same_values({2, 4, 1, 3}, {1, 2, 3, 4})
	end)
  it("negative", function()
		assert.not_same_values({"seven"}, {"one", "two", "three", "four"})
	end)
  it("nil in array", function()
		assert.not_same_values(nil, {"1", "2", nil, "3", "4"})
		assert.not_same_values(nil, {1, nil, 3})
		assert.not_same_values(nil, {nil, 2})
	end)
  it("nil not in array", function()
		assert.not_same_values(nil, {"one", "two", "three", "four"})
		assert.not_same_values(nil, {})
	end)
  it("nil", function()
		assert.has_error(function() assert.same_values() end)
		assert.has_error(function() assert.same_values(nil) end)
		assert.has_error(function() assert.same_values("seven") end)
		assert.has_error(function() assert.same_values("seven", nil) end)
	end)
end)
