describe("assert z", function()
	setup(function() require "t" end)
  it("positive", function()
    assert.z()
    assert.z(nil)
    assert.z(" ")
    assert.z("")
    assert.z(false)
    assert.z({})
    assert.z(0)
    assert.z("0")
  end)
  it("negative", function()
    assert.not_z("some")
    assert.not_z(true)
    assert.not_z({7})
    assert.not_z(1)
    assert.not_z("1")
  end)
end)
